### PR TITLE
fix bad ssl refererence in mac build

### LINKED ISSUE #1438: OpenLDAPClient_jll fails to load on macOS
See https://travis-ci.org/github/felipenoris/LDAPClient.jl/jobs/716752103

```
Downloading artifact: OpenLDAPClient
######################################################################## 100.0%
Downloading artifact: PCRE
######################################################################## 100.0%
Downloading artifact: OpenSSL
######################################################################## 100.0%
ERROR: LoadError: InitError: could not load library "/Users/travis/.julia/artifacts/b5532cbc6201f78b80d177b62303c238f74e2ddc/lib/libldap.dylib"
dlopen(/Users/travis/.julia/artifacts/b5532cbc6201f78b80d177b62303c238f74e2ddc/lib/libldap.dylib, 1): Library not loaded: /workspace/destdir/lib/liblber-2.4.2.dylib
  Referenced from: /Users/travis/.julia/artifacts/b5532cbc6201f78b80d177b62303c238f74e2ddc/lib/libldap.dylib
  Reason: image not found
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
 [2] dlopen at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
 [3] __init__() at /Users/travis/.julia/packages/OpenLDAPClient_jll/BOQyS/src/wrappers/x86_64-apple-darwin14.jl:384
```

### PR DESCRIPTION
**Pull request by aviks**
fix #1438

### CODE REVIEW

**Comment by giordano** [comment]
Why FreeBSD, why?!?!

**Comment by giordano** [comment]
For the record, this is failing with
```
[18:09:35] /opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-ld --sysroot=/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root --eh-frame-hdr -dynamic-linker /libexec/ld-elf.so.1 --hash-style=both --enable-new-dtags -o urltest /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib/crt1.o /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib/crti.o /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib/crtbegin.o -L/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/lib -L/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib urltest.o ./.libs/libldap.so /workspace/srcdir/openldap-2.4.50/libraries/liblber/.libs/liblber.so ../../libraries/liblber/.libs/liblber.so ../../libraries/liblutil/liblutil.a -lssl -lcrypto -rpath /workspace/srcdir/openldap-2.4.50/libraries/libldap/.libs -rpath /workspace/srcdir/openldap-2.4.50/libraries/liblber/.libs -rpath /workspace/destdir/lib -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib/crtend.o /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib/crtn.o
[18:09:35] ./.libs/libldap.so: undefined reference to `ERR_free_strings'
[18:09:35] ./.libs/libldap.so: undefined reference to `sk_free'
[18:09:35] ./.libs/libldap.so: undefined reference to `sk_value'
[18:09:35] ./.libs/libldap.so: undefined reference to `sk_new_null'
[18:09:35] ./.libs/libldap.so: undefined reference to `SSL_library_init'
[18:09:35] ./.libs/libldap.so: undefined reference to `RAND_egd'
[18:09:35] ./.libs/libldap.so: undefined reference to `SSLv23_method'
[18:09:35] ./.libs/libldap.so: undefined reference to `SSL_CTX_set_tmp_rsa_callback'
[18:09:35] ./.libs/libldap.so: undefined reference to `EVP_cleanup'
[18:09:35] ./.libs/libldap.so: undefined reference to `sk_num'
[18:09:35] ./.libs/libldap.so: undefined reference to `OpenSSL_add_all_digests'
[18:09:35] ./.libs/libldap.so: undefined reference to `SSL_load_error_strings'
[18:09:35] ./.libs/libldap.so: undefined reference to `CRYPTO_add_lock'
[...]
```
We may have some problems with our build of OpenSSL for FreeBSD: for example our `libssl.so` doesn't have the symbol `SSL_library_init`, while the library in the root file system has it:
```
sandbox:${WORKSPACE} # nm -D /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root/usr/lib/libssl.so | grep SSL_library_init
000000000001f920 T SSL_library_init
```
I'm tempted by not deleting the files when building for FreeBSD....

**Comment by Keno** [comment]
Are we tracking rm'ing openssl from the macos SDK we ship somewhere?

**Comment by giordano** [comment]
Now yes: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/891

File: O/OpenLDAPClient/build_tarballs.jl [hunk 1]
```diff
@@ -28,7 +28,29 @@ if [[ "${target}" == *-mingw* ]]; then
...
+    # The mac build tries to pick up libraries from system root, but our build
+    # of OpenSSL seems to be incomplete (it's missing some important symbols),
+    # so let's keep this file for FreeBSD until we get reports it doesn't work.
+    rm -f /opt/${target}/${target}/sys-root/usr/lib/libcrypto.*
+    rm -f /opt/${target}/${target}/sys-root/usr/lib/libssl.*
+    rm -f /opt/${target}/${target}/sys-root/usr/lib/libsasl2.*
+    rm -f /lib/libcrypto.so*
+    rm -f /usr/lib/libcrypto.so*
+    rm -f /lib/libssl.so*
+    rm -f /usr/lib/libssl.so*
```
Comment (staticfloat) [inline O/OpenLDAPClient/build_tarballs.jl:41]: I can just feel your zealous fury as you delete every OpenSSL-related library on your system.  😂 

Those are host SSL libraries; you shouldn't delete these or else you won't be able to do stuff like `curl`.  :P Only the `/opt/${target}` libraries will be used by the compiler, because that's the only place that gets searched.  Even if it did search `/lib`, it would not link in these libraries because they won't match the compiler's target (except when `${target}` == `x86_64-linux-musl`).

Comment (giordano) [reply O/OpenLDAPClient/build_tarballs.jl:41]: In the OpenSSH builder for `x86_64-linux-musl`, the build system was picking up the system OpenSSL.

> you shouldn't delete these or else you won't be able to do stuff like curl.

Do we want to run `curl` during a build? :wink:
